# Generated by Django 6.0.7 on 2026-08-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(default='Action', max_length=50)),
                ('video_url', models.URLField(help_text='Direct MP4 or video embed link')),
                ('thumbnail_url', models.URLField(help_text='Image URL for video poster')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
