# Generated by Django 6.0.7 on 2026-08-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_remove_video_thumbnail_url_remove_video_video_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload MP4 or MOV film file directly', null=True, upload_to='videos/'),
        ),
    ]
