# Generated by Django 6.0.7 on 2026-08-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_video_video_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Internal campaign title', max_length=100)),
                ('ad_video', models.FileField(help_text='Upload short MP4 ad video (15-30s)', upload_to='ads/')),
                ('destination_url', models.URLField(blank=True, help_text="URL to open when user clicks 'Visit Sponsor'", null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Toggle to activate or pause this ad campaign')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload MP4 or MOV film file', null=True, upload_to='videos/'),
        ),
    ]
