# Generated by Django 6.0.7 on 2026-08-04 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_advertisement_alter_video_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='destination_url',
            field=models.URLField(blank=True, help_text='Sponsor link', null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='title',
            field=models.CharField(help_text='Campaign title', max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload MP4 film file', null=True, upload_to='videos/'),
        ),
        migrations.CreateModel(
            name='MidRollAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_seconds', models.PositiveIntegerField(help_text='Time in SECONDS into the movie when this ad should trigger (e.g. 900 for 15 mins)')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.advertisement')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midroll_ads', to='web.video')),
            ],
            options={
                'ordering': ['timestamp_seconds'],
            },
        ),
    ]
