# Generated by Django 6.0.7 on 2026-08-05 16:21

import cloudinary_storage.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_advertisement_destination_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='midrollad',
            options={},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='midrollad',
            old_name='advertisement',
            new_name='ad',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='ad_video',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='midrollad',
            name='timestamp_seconds',
        ),
        migrations.RemoveField(
            model_name='watchprogress',
            name='duration_seconds',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='ad_video_file',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='ads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mkv', 'webm'])]),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='external_ad_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='midrollad',
            name='time_in_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Timestamp in seconds to trigger ad (e.g., 300 = 5 minutes mark)'),
        ),
        migrations.AddField(
            model_name='video',
            name='external_video_url',
            field=models.URLField(blank=True, help_text='Optional: Paste direct video link if not uploading a file', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='destination_url',
            field=models.URLField(default='https://google.com', max_length=1000),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Horror', 'Horror'), ('Sci-Fi', 'Sci-Fi'), ('Romance', 'Romance'), ('Thriller', 'Thriller'), ('Documentary', 'Documentary')], default='Action', max_length=50),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload video file (MP4, MKV, AVI, MOV, WEBM)', null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mkv', 'avi', 'mov', 'webm'])]),
        ),
        migrations.AlterField(
            model_name='watchprogress',
            name='last_position_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
